# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 母鸡好多
email: guoweist@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 喜欢数据，从事自动化。所以学习数据科学，钻研自动化。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 没有
github_username:  DukasGuo

# Build settings
markdown: kramdown

port: 5001
